services:
  schooldb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentmgmtdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data