spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5431/studentmgmtdb
    username: root
    password: password
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8082

jwt:
  secret: vgUOp6+IKgzx9rEN0uxVHTcLONT/0kuuNWV8J5WNliudPE69d/nr6Di+txIAaglf1Gn3hjCBCjRmxH7xZPw8rQ==
  expiration: 86400000