spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:postgresql://localhost:5431/studentmgmtdb
    username: "root"
    password: "password"
    driver-class-name: org.postgresql.Driver

server:
  port: 8083

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: 6zo3SQ6GgR0HBB973V7baxD/TPCEzPkNJNB602sJ1Otr6VksrcknFRN39Clu83/11ynxRCuP5c1Afj/fTDDvUA==
  expiration: 86400000

user-service:
    base-url: http://localhost:8082

